name: Dumper_payload

on:
 workflow_dispatch: 
  inputs:
    url:
      description: "paste_Rom_url_here" 
      required: true 
      type: string
          
env:
  TZ: Asia/Kolkata
  GITHUB_TOKEN: ${{ secrets.GH_PAT }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download Rom
        run: |
          curl -L "${{ inputs.url }}" -o "rom.zip"
          unzip rom.zip
          ls -lh

      - name: Clone dumper into root
        run: |
          git clone https://github.com/vm03/payload_dumper.git
          pip install protobuf six bsdiff4 brotli zstandard fsspec requests aiohttp
          ls -lh payload_dumper

      - name: Copy payload.bin
        run: |
          cp payload.bin ./payload_dumper
          ls -lh payload_dumper

      - name: Extract payload
        run: |
          cd payload_dumper
          python3 payload_dumper.py payload.bin
          ls -lh output

      - name: 📦 Upload payload to GitHub Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          tag_name: "payload"
          name: boot_img_dumper
          body: source "${{ inputs.url }}"
          files: "payload_dumper/output/*.img"
